const actionTypes = {
  FETCH_DATA: 'FETCH_DATA',
  FETCH_EMPLOYEES_SUCCESS: 'FETCH_EMPLOYEES_SUCCESS',
  ADD_EMPLOYEE: 'ADD_EMPLOYEE',
  FETCH_SALES_SUCCESS: 'FETCH_SALES_SUCCESS',
  FETCH_PRODUCTS_SUCCESS: 'FETCH_PRODUCTS_SUCCESS',
  FETCH_PRODUCT_SUCCESS: 'FETCH_PRODUCT_SUCCESS',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  USER_LOADING: 'USER_LOADING',
  SHOW_SUCCESS: 'SHOW_SUCCESS',
  CLEAR_SUCCESS: 'CLEAR_SUCCESS',
  USER_LOADED: 'USER_LOADED',
  AUTH_ERROR: 'AUTH_ERROR',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  SHOW_ERRORS: 'SHOW_ERRORS',
  CLEAR_ERRORS: 'CLEAR_ERRORS',
};

export default actionTypes;
