const actionTypes = {
  FETCH_DATA: 'FETCH_DATA',
  FETCH_EMPLOYEES_SUCCESS: 'FETCH_EMPLOYEES_SUCCESS',
  ADD_EMPLOYEE: 'ADD_EMPLOYEE',
  FETCH_SALES_SUCCESS: 'FETCH_SALES_SUCCESS',
};

export default actionTypes;
