const actionTypes = {
  FETCH_EMPLOYEES: 'FETCH_EMPLOYEES',
  SHOW_EMPLOYEES: 'SHOW_EMPLOYEES',
  ADD_EMPLOYEE: 'ADD_EMPLOYEE',
  SHOW_SALES: 'SHOW_SALES',
  FETCH_EMPLOYEES_SUCCESS: 'FETCH_EMPLOYEES_SUCCESS'
};

export default actionTypes;
